owner: redhatcloudx
repo: upptime

sites:
  - name: CID Frontend
    url: https://imagedirectory.cloud/
  - name: AWS CID Data
    url: https://imagedirectory.cloud/raw/aws/us-east-1.json
  - name: Azure CID Data
    url: https://imagedirectory.cloud/raw/azure/eastus.json
  - name: Google CID Data
    url: https://imagedirectory.cloud/raw/google/global.json
  # - name: Failure test
  #   url: https://imagedirectory.cloud/doesnotexist.html

status-website:
  cname: status.imagedirectory.cloud
  # baseUrl: /your-repo-name
  theme: ocean
  logoUrl: https://avatars.githubusercontent.com/u/114747495?s=200&v=4
  name: Red Hat Cloud Experience Team
  introTitle: "Monitoring for CloudX team infrastructure."
  introMessage: "Improving the Red Hat cloud experience one virtual CPU at a time. 😉"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/redhatcloudx/upptime

assignees:
  - fkolwa
  - major
  - miyunari
